export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


export const CATEGORY_START = 'CATEGORY_START';
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS';
export const CATEGORY_FAIL = 'CATEGORY_FAIL';
export const REMOVED_CATEGORY = 'REMOVED_CATEGORY';
export const CATEGORY_LIST = 'CATEGORY_LIST';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const START_EDIT_CATEGORY = 'START_EDIT_CATEGORY';
export const GET_EDIT_CATEGORY = 'GET_EDIT_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

//Modality
export const GET_MODALITIES = 'GET_MODALITIES';
export const CLEAR_MODALITY = 'CLEAR_MODALITY';
export const MODALITY_ERROR = 'MODALITY_ERROR';
export const DELETE_MODALITY = 'DELETE_MODALITY';
export const CREATE_MODALITY = 'CREATE_MODALITY';
export const UPDATE_MODALITY = 'UPDATE_MODALITY';

//Icons
export const GET_ICONS = 'GET_ICONS';
export const CLEAR_ICONS = 'CLEAR_ICONS';
export const ICONS_ERROR = 'ICONS_ERROR';
export const CREATE_ICON = 'CREATE_ICON';
export const DELETE_ICON = 'DELETE_ICON';
export const UPDATE_ICON = 'UPDATE_ICON';

export const GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID';